### PR TITLE
Detect category B correctly for mentally dependent

### PR DESCRIPTION
**Pull request by SamVerschueren**
Before:

image

After:

image

--------------
This is the reason why it changed

image

### CODE REVIEW

**Review by SimonJang — APPROVED** [review]
Looks good!

**Comment by bartcallant** [comment]
Could you paste a link to the full flow chart? I'm not completely sure everything is correct.

Or it might just be to late to think correctly on my end...

**Comment by SamVerschueren** [comment]
One thing that should still be figured out before we can merge this. I'll keep you posted.

**Comment by SamVerschueren** [comment]
This should be the final version

Screen Shot 2019-08-14 at 13 44 28

**Review by IbenTesara — APPROVED** [review]

**Review by bartcallant — APPROVED** [review]

**Pull request merged**
